### ISSUE TITLE
Pre-selected child not work

### ISSUE THREAD

**Issue by piperino11** [soyiatgit/p-group-multiselect#15]
![image](https://user-images.githubusercontent.com/37184273/126797166-067789fe-b1c0-43a9-9aac-40331de590c8.png)
If I put some objects in "selectedChildOptions" by default, they are not "checked"
![image](https://user-images.githubusercontent.com/37184273/126797579-8e671f26-3330-45b8-ad80-fa288eb9525b.png)
but the label is recognized
![image](https://user-images.githubusercontent.com/37184273/126797632-9150cd0e-69ee-40c5-b33e-f722ca0e8dec.png)

**Comment by soyiatgit** [comment]
I checked it and it seems to work as expected. My assumption is that you are trying to set the whole child option object in the selectedChildOptions. You don't have to set whole of it, just the value of it. I checked with the following code and it worked fine.

```
ngOnInit() {
    this.options[1].value.selectedChildOptions = [this.options[1].value.childOptions[2].value];
    // this.options[1].value.selectedChildOptions.push(this.options[1].value.childOptions[2]);  // don't do this
   // this.options[1].value.selectedChildOptions.push(this.options[1].value.childOptions[2].value); // do this, just push the value
  }
```

I am closing the issue for now. Please feel free to open another one, if it doesn't work for you. Also please add the code you are trying to set the default values.
